### ISSUE TITLE
Put code snippets in backticks on readme.

### ISSUE THREAD

**Issue by sawaiz** [MontySteele/cosmicDataServer#1]
Markdown has Backticks (\`) used to denote inline code and (\`\`\`) tipple backticks to denote block code. This should make the readme easier to follow.

```
```cat hello.txt```
```

Renders as 
```cat hello.txt```

Each detector's data must be concatenated into a file called `'all.dat' cat * > all.dat`

The `all.dat` file must be in the same directory as the `formatLog.C` program. This program will modify the data, then place it in an `allFormat.dat` file for processing.

```
sudo g++ formatLog.C sudo ./a.out
```

**Comment by MontySteele** [comment]
Properly labelled code
